server:
  port: 8011

spring:
  profiles: dev
eureka:
  instance:
    hostname: ${eureka.instance}
  client:
    register-with-eureka: false # 是否把自己作为服务注册到其他服务中心注册
    fetch-registry: false # 是否与其他的服务中心同步服务列表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
  server:
    enable-self-preservation: false


---
spring:
  profiles: prod
eureka:
  instance:
    hostname: ${eureka.instance}
  client:
    register-with-eureka: false # 是否把自己作为服务注册到其他服务中心注册
    fetch-registry: false # 是否与其他的服务中心同步服务列表
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
  server:
    enable-self-preservation: false

